package com.lmnoppy.api.covid.model.enums;

import lombok.Getter;

/**
 * All metrics avalable from the NHS Developer page: https://coronavirus.data.gov.uk/metrics
 *
 * metricNameValue - the actual metric name on NHS guide
 * metricDescription - description of what data the metric provides
 * isDeprecated - is the metric deprecated or not?
 *
 * Yes I will set all the ENUMS to upper case and add underscores....eventually.
 */

@Getter
public enum Metrics {

    DATE("date", null, false),
    AREA_NAME("areaName", null, false),
    AREA_CODE("areaCode", null, false),
    NEW_CASES_BY_PUBLISH_DATE("newCasesByPublishDate", null, false),
    CUM_CASES_BY_PUBLISH_DATE("cumCasesByPublishDate", "Cumulative cases by publish date", false),
    CUM_CASES_BY_PUBLISH_DATE_RATE("cumCasesByPublishDateRate", "Cumulative cases by publish date rate", false),
    NEW_DEATHS_28_DAYS_BY_PUBLISH_DATE("newDeaths28DaysByPublishDate", null, false),
    CUM_DEATHS_28_DAYS_BY_PUBLISH_DATE("cumDeaths28DaysByPublishDate", null, false),
    COVID_OCCUPIED_MV_BEDS("covidOccupiedMVBeds", "COVID occupied mechanical ventilator beds", false),
    CUM_ADMISSIONS("cumAdmissions", "Cumulative admissions", false),
    CUM_ADMISSIONS_BY_AGE("cumAdmissionsByAge", "Cumulative admissions by age", false),
    CUM_ANTIBODY_TESTS_BY_PUBLISH_DATE("cumAntibodyTestsByPublishDate", "Cumulative antibody tests by publish date", false),
    CUM_CASES_LFD_CONFIRMED_PCR_BY_SPECIMEN_DATE("cumCasesLFDConfirmedPCRBySpecimenDate", "Cumulative cases LFD confirmed by PCR by specimen date", false),
    CUM_CASES_LFD_ONLY_BY_SPECIMEN_DATE("cumCasesLFDOnlyBySpecimenDate", "Cumulative cases LFD-only by specimen date", false),
    CUM_CASES_PCR_ONLY_BY_SPECIMEN_DATE("cumCasesPCROnlyBySpecimenDate", "Cumulative cases PCR only by specimen date", false),
    CUM_DAILY_NSO_DEATHS_BY_DEATH_DATE("cumDailyNsoDeathsByDeathDate", "Cumulative daily national statistics office deaths by death date", false),
    CUM_DEATHS_28DAYS_BY_DEATH_DATE("cumDeaths28DaysByDeathDate", "Cumulative deaths within 28 days of a positive test by death date", false),
    CUM_DEATHS_28DAYS_BY_DEATH_DATE_RATE("cumDeaths28DaysByDeathDateRate", "Cumulative deaths within 28 days of a positive test rate by death date", false),
    CUM_DEATHS_28DAYS_BY_PUBLISH_DATE("cumDeaths28DaysByPublishDate", "Cumulative deaths within 28 days of a positive test by publish date", false),
    CUM_DEATHS_28DAYS_BY_PUBLISH_DATE_RATE("cumDeaths28DaysByPublishDateRate", "Cumulative deaths within 28 days of a positive test rate by publish date", false),
    CUM_DEATHS60_DAYS_BY_DEATH_DATE("cumDeaths60DaysByDeathDate", "Cumulative deaths within 60 days of a positive test by death date", false),
    CUM_DEATHS60_DAYS_BY_DEATH_DATE_RATE("cumDeaths60DaysByDeathDateRate", "Cumulative deaths within 60 days of a positive test rate by death date", false),
    CUM_DEATHS60_DAYS_BY_PUBLISH_DATE("cumDeaths60DaysByPublishDate", "Cumulative deaths within 60 days of a positive test by publish date", false),
    CUM_DEATHS60_DAYS_BY_PUBLISH_DATE_RATE("cumDeaths60DaysByPublishDateRate", "Cumulative deaths within 60 days of a positive test rate by publish date", false),
    CUM_DEATHS_BY_DEATH_DATE("cumDeathsByDeathDate", "Cumulative deaths by death date", false),
    CUM_DEATHS_BY_DEATH_DATE_RATE("cumDeathsByDeathDateRate", "Cumulative deaths by death date rate", false),
    CUM_DEATHS_BY_PUBLISH_DATE("cumDeathsByPublishDate", "Cumulative deaths by publish date", false),
    CUM_DEATHS_BY_PUBLISH_DATE_RATE("cumDeathsByPublishDateRate", "Cumulative deaths by publish date rate", false),
    CUM_FIRST_EPISODES_BY_SPECIMEN_DATE("cumFirstEpisodesBySpecimenDate", "Cumulative first infection episodes by specimen date", false),
    CUM_FIRST_EPISODES_BY_SPECIMEN_DATE_RATE("cumFirstEpisodesBySpecimenDateRate", "Cumulative first infection episodes rate by specimen date", false),
    CUM_LFD_TESTS_BY_SPECIMEN_DATE("cumLFDTestsBySpecimenDate", "Cumulative LFD tests", false),
    CUM_ONS_DEATHS_BY_REGISTRATION_DATE("cumOnsDeathsByRegistrationDate", "Cumulative Office for National Statistics deaths by registration date", false),
    CUM_ONS_DEATHS_BY_REGISTRATION_DATE_RATE("cumOnsDeathsByRegistrationDateRate", "Cumulative ONS deaths by registration date rate", false),
    CUM_PCR_TESTS_BY_PUBLISH_DATE("cumPCRTestsByPublishDate", "Cumulative PCR tests by publish date", false),
    CUM_PCR_TESTS_BY_SPECIMEN_DATE("cumPCRTestsBySpecimenDate", "Total PCR tests by specimen date", false),
    CUM_PEOPLE_VACCINATED_BOOSTER_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedBoosterDoseByPublishDate", "Cumulative people vaccinated booster dose by publish date", false),
    CUM_PEOPLE_VACCINATED_COMPLETE_BY_PUBLISH_DATE("cumPeopleVaccinatedCompleteByPublishDate", "Cumulative people vaccinated complete by publish date", false),
    CUM_PEOPLE_VACCINATED_COMPLETE_BY_VACCINATION_DATE("cumPeopleVaccinatedCompleteByVaccinationDate", "Cumulative people fully vaccinated by vaccination date", false),
    CUM_PEOPLE_VACCINATED_FIRST_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedFirstDoseByPublishDate", "Cumulative people vaccinated 1st dose by publish date", false),
    CUM_PEOPLE_VACCINATED_FIRST_DOSE_BY_VACCINATION_DATE("cumPeopleVaccinatedFirstDoseByVaccinationDate", "Cumulative people vaccinated 1st dose by vaccination date", false),
    CUM_PEOPLE_VACCINATED_SECOND_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedSecondDoseByPublishDate", "Cumulative people vaccinated 2nd dose by publish date", false),
    CUM_PEOPLE_VACCINATED_SECOND_DOSE_BY_VACCINATION_DATE("cumPeopleVaccinatedSecondDoseByVaccinationDate", "Cumulative people vaccinated 2nd dose by vaccination date", false),
    CUM_PEOPLE_VACCINATED_THIRD_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedThirdDoseByPublishDate", "Cumulative people vaccinated 3rd dose by publish date", false),
    CUM_PEOPLE_VACCINATED_THIRD_INJECTION_BY_PUBLISH_DATE("cumPeopleVaccinatedThirdInjectionByPublishDate", "Cumulative people vaccinated with a booster dose plus new people vaccinated with a third dose by publish date", false),
    CUM_PEOPLE_VACCINATED_THIRD_INJECTION_BY_VACCINATION_DATE("cumPeopleVaccinatedThirdInjectionByVaccinationDate", "Cumulative people vaccinated booster or third dose by vaccination date", false),
    CUM_PILLAR_FOUR_TESTS_BY_PUBLISH_DATE("cumPillarFourTestsByPublishDate", "Cumulative pillar 4 tests by publish date", false),
    CUM_PILLAR_ONE_TESTS_BY_PUBLISH_DATE("cumPillarOneTestsByPublishDate", "Cumulative pillar 1 tests by publish date", false),
    CUM_PILLAR_ONE_TWO_TESTS_BY_PUBLISH_DATE("cumPillarOneTwoTestsByPublishDate", "Cumulative pillars 1 and 2 tests by publish date", false),
    CUM_PILLAR_THREE_TESTS_BY_PUBLISH_DATE("cumPillarThreeTestsByPublishDate", "Cumulative pillar 3 tests by publish date", false),
    CUM_PILLAR_TWO_TESTS_BY_PUBLISH_DATE("cumPillarTwoTestsByPublishDate", "Cumulative pillar 2 tests by publish date", false),
    CUM_REINFECTIONS_BY_SPECIMEN_DATE("cumReinfectionsBySpecimenDate", "Cumulative reinfections by specimen date", false),
    CUM_REINFECTIONS_BY_SPECIMEN_DATE_RATE("cumReinfectionsBySpecimenDateRate", "Cumulative reinfections rate by specimen date", false),
    CUM_TESTS_BY_PUBLISH_DATE("cumTestsByPublishDate", "Cumulative tests by publish date", false),
    CUM_VACCINATION_BOOSTER_DOSE_UPTAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationBoosterDoseUptakeByPublishDatePercentage", "Cumulative percentage of people vaccinated with a booster dose by publish date", false),
    CUM_VACCINATION_COMPLETE_COVERAGE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationCompleteCoverageByPublishDatePercentage", "Cumulative vaccination complete coverage by publish date percentage", false),
    CUM_VACCINATION_COMPLETE_COVERAGE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationCompleteCoverageByVaccinationDatePercentage", "Cumulative percentage of people fully vaccinated by vaccination date", false),
    CUM_VACCINATION_FIRST_DOSE_UPTAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationFirstDoseUptakeByPublishDatePercentage", "Cumulative vaccination 1st dose uptake by publish date percentage", false),
    CUM_VACCINATION_FIRST_DOSE_UPTAKE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationFirstDoseUptakeByVaccinationDatePercentage", "Cumulative percentage of people vaccinated with a first dose by vaccination date", false),
    CUM_VACCINATION_SECOND_DOSE_UP_TAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationSecondDoseUptakeByPublishDatePercentage", "Cumulative vaccination 2nd dose uptake by publish date percentage", false),
    CUM_VACCINATION_SECOND_DOSE_UPTAKE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationSecondDoseUptakeByVaccinationDatePercentage", "Cumulative percentage of second dose vaccination uptake by vaccination date", false),
    CUM_VACCINATION_THIRD_INJECTION_UPTAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationThirdInjectionUptakeByPublishDatePercentage", "Cumulative percentage of people vaccinated with a booster dose plus people vaccinated with third dose by publish date", false),
    CUM_VACCINATION_THIRD_INJECTION_UPTAKE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationThirdInjectionUptakeByVaccinationDatePercentage", "Cumulative percentage of people vaccinated with a booster or third dose by vaccination date", false),
    CUM_VACCINES_GIVEN_BY_PUBLISH_DATE("cumVaccinesGivenByPublishDate", "Cumulative vaccines given by publish date", false),
    CUM_VIRUS_TESTS_BY_PUBLISH_DATE("cumVirusTestsByPublishDate", "Cumulative virus tests", false),
    CUM_VIRUS_TESTS_BY_SPECIMEN_DATE("cumVirusTestsBySpecimenDate", "Total virus tests by specimen date", false),
    CUM_WEEKLY_NSO_DEATHS_BY_REG_DATE("cumWeeklyNsoDeathsByRegDate", "Cumulative weekly national statistics office deaths by registration date", false),
    CUM_WEEKLY_NSO_DEATHS_BY_REG_DATE_RATE("cumWeeklyNsoDeathsByRegDateRate","Cumulative weekly national statistics office deaths by registration date rate", false),
    FEMALE_CASES("femaleCases","Female cases", false),
    FEMALE_DEATHS_28DAYS("femaleDeaths28Days","Female deaths within 28 days of a positive test", false),
    HOSPITAL_CASES("hospitalCases","Patients in hospital", false),
    MALE_CASES("maleCases","Male cases", false),
    MALE_DEATHS_28DAYS("maleDeaths28Days","Male deaths within 28 days of a positive test", false),
    NEW_ADMISSIONS("newAdmissions","New admissions", false),
    newAdmissionsChange("newAdmissionsChange","New admissions change", false),
    newAdmissionsChangePercentage("newAdmissionsChangePercentage","New admissions change percentage", false),
    newAdmissionsDirection("newAdmissionsDirection","New admissions direction", false),
    newAdmissionsRollingRate("newAdmissionsRollingRate","New admissions rolling rate", false),
    newAdmissionsRollingSum("newAdmissionsRollingSum","New admissions rolling sum", false),
    newAntibodyTestsByPublishDate("newAntibodyTestsByPublishDate","New antibody tests by publish date", false),
    newCasesByPublishDate("newCasesByPublishDate","New cases by publish date", false),
    newCasesByPublishDateChange("newCasesByPublishDateChange","New cases by publish date change", false),
    newCasesByPublishDateChangePercentage("newCasesByPublishDateChangePercentage","New cases percentage change by publish date", false),
    newCasesByPublishDateDirection("newCasesByPublishDateDirection","New cases by publish date direction", false),
    newCasesByPublishDateRollingSum("newCasesByPublishDateRollingSum","New cases by publish date rolling sum", false),
    newCasesBySpecimenDate("newCasesBySpecimenDate","New cases by specimen date", false),
    newCasesBySpecimenDateAgeDemographics("newCasesBySpecimenDateAgeDemographics","New cases by specimen date age demographics", false),
    newCasesBySpecimenDateChange("newCasesBySpecimenDateChange","New cases by specimen date change", false),
    newCasesBySpecimenDateChangePercentage("newCasesBySpecimenDateChangePercentage","New cases percentage change by specimen date", false),
    newCasesBySpecimenDateDirection("newCasesBySpecimenDateDirection","New cases by specimen date direction", false),
    newCasesBySpecimenDateRollingRate("newCasesBySpecimenDateRollingRate","New cases rolling rate by specimen date", false),
    newCasesBySpecimenDateRollingSum("newCasesBySpecimenDateRollingSum","New cases by specimen date rolling sum", false),
    newCasesLFDConfirmedPCRBySpecimenDate("newCasesLFDConfirmedPCRBySpecimenDate","New cases LFD confirmed by PCR by specimen date", false),
    newCasesLFDConfirmedPCRBySpecimenDateRollingRate("newCasesLFDConfirmedPCRBySpecimenDateRollingRate","New cases LFD confirmed by PCR rolling rate by specimen date", false),
    newCasesLFDConfirmedPCRBySpecimenDateRollingSum("newCasesLFDConfirmedPCRBySpecimenDateRollingSum","New cases LFD confirmed by PCR rolling sum by specimen date", false),
    newCasesLFDOnlyBySpecimenDate("newCasesLFDOnlyBySpecimenDate","New cases LFD only by specimen date", false),
    newCasesLFDOnlyBySpecimenDateRollingRate("newCasesLFDOnlyBySpecimenDateRollingRate","New cases LFD only rolling rate by specimen date", false),
    newCasesLFDOnlyBySpecimenDateRollingSum("newCasesLFDOnlyBySpecimenDateRollingSum","New cases LFD only rolling sum by specimen date", false),
    newCasesPCROnlyBySpecimenDate("newCasesPCROnlyBySpecimenDate","New cases PCR only by specimen date", false),
    newCasesPCROnlyBySpecimenDateRollingRate("newCasesPCROnlyBySpecimenDateRollingRate","New cases PCR only by specimen date rolling rate", false),
    newCasesPCROnlyBySpecimenDateRollingSum("newCasesPCROnlyBySpecimenDateRollingSum","New cases PCR only by specimen date rolling sum", false),
    newDailyNsoDeathsByDeathDate("newDailyNsoDeathsByDeathDate","New daily national statistics office deaths by death date", false),
    newDeaths28DaysByDeathDate("newDeaths28DaysByDeathDate","New deaths within 28 days of a positive test by death date", false),
    newDeaths28DaysByDeathDateAgeDemographics("newDeaths28DaysByDeathDateAgeDemographics","New deaths 28 days by death date age demographics", false),
    newDeaths28DaysByDeathDateChangePercentage("newDeaths28DaysByDeathDateChangePercentage","New deaths within 28 days of a positive test change percentage by death date", false),
    newDeaths28DaysByDeathDateDirection("newDeaths28DaysByDeathDateDirection","New deaths within 28 days of a positive test direction by death date", false),
    newDeaths28DaysByDeathDateRate("newDeaths28DaysByDeathDateRate","New deaths within 28 days of a positive test rate by death date", false),
    newDeaths28DaysByDeathDateRollingRate("newDeaths28DaysByDeathDateRollingRate","New deaths within 28 days of a positive test rolling rate by death date", false),
    newDeaths28DaysByDeathDateRollingSum("newDeaths28DaysByDeathDateRollingSum","New deaths within 28 days of a positive test rolling sum test by death date", false),
    newDeaths28DaysByPublishDate("newDeaths28DaysByPublishDate","New deaths 28 days of a positive test by publish date", false),
    newDeaths28DaysByPublishDateChange("newDeaths28DaysByPublishDateChange","New deaths within 28 days of a positive test by publish date change", false),
    newDeaths28DaysByPublishDateChangePercentage("newDeaths28DaysByPublishDateChangePercentage","New deaths within 28 days of a positive test change percentage by publish date", false),
    newDeaths28DaysByPublishDateDirection("newDeaths28DaysByPublishDateDirection","New deaths within 28 days of a positive test direction by publish date", false),
    newDeaths28DaysByPublishDateRollingSum("newDeaths28DaysByPublishDateRollingSum","New deaths within 28 days of a positive test rolling sum by publish date", false),
    newDeaths60DaysByDeathDate("newDeaths60DaysByDeathDate","New deaths within 60 days of a positive test by death date", false),
    newDeaths60DaysByDeathDateRate("newDeaths60DaysByDeathDateRate","New deaths within 60 days of a positive test rate by death date", false),
    newDeaths60DaysByDeathDateRollingRate("newDeaths60DaysByDeathDateRollingRate","New deaths within 60 days of a positive test rolling rate by death date", false),
    newDeaths60DaysByDeathDateRollingSum("newDeaths60DaysByDeathDateRollingSum","New deaths within 60 days of a positive test rolling sum by death date", false),
    newDeaths60DaysByPublishDate("newDeaths60DaysByPublishDate","New deaths within 60 days of a positive test by publish date", false),
    newDeathsByDeathDate("newDeathsByDeathDate","New deaths by death date", false),
    newDeathsByDeathDateRate("newDeathsByDeathDateRate","New deaths by death date rate", false),
    newDeathsByDeathDateRollingRate("newDeathsByDeathDateRollingRate","New deaths by death date rolling rate", false),
    newDeathsByDeathDateRollingSum("newDeathsByDeathDateRollingSum","New deaths by death date rolling sum", false),
    newDeathsByPublishDate("newDeathsByPublishDate","New deaths by publish date", false),
    newFirstEpisodesBySpecimenDate("newFirstEpisodesBySpecimenDate","New first episodes by specimen date", false),
    newFirstEpisodesBySpecimenDateChange("newFirstEpisodesBySpecimenDateChange","New first episodes by specimen date change", false),
    newFirstEpisodesBySpecimenDateChangePercentage("","New first episodes change percentage by specimen date", false),
    newFirstEpisodesBySpecimenDateDirection("","New first episodes direction by specimen date", false),
    newFirstEpisodesBySpecimenDateRollingRate("","New first episodes rolling rate by specimen date", false),
    newFirstEpisodesBySpecimenDateRollingSum("","New first infection episodes rolling sum by specimen date", false),
    newLFDTestsBySpecimenDate("","New LFD tests", false),
    newOnsDeathsByRegistrationDate("","New Office for National Statistics deaths by registration date", false),
    newPCRTestsByPublishDate("","New PCR tests by publish date", false),
    newPCRTestsByPublishDateChange("","New PCR tests by publish date change", false),
    newPCRTestsByPublishDateChangePercentage("","New PCR tests by publish date change percentage", false),
    newPCRTestsByPublishDateDirection("","New PCR tests by publish date direction", false),
    newPCRTestsByPublishDateRollingSum("","New PCR tests by publish date rolling sum", false),
    newPCRTestsBySpecimenDate("","New PCR tests by specimen date", false),
    newPeopleReceivingFirstDose("","New people receiving 1st dose", false),
    newPeopleReceivingSecondDose("","New people receiving 2nd dose", false),
    newPeopleVaccinatedBoosterDoseByPublishDate("","New people vaccinated with a booster dose by publish date", false),
    newPeopleVaccinatedCompleteByPublishDate("","New people vaccinated complete by publish date", false),
    newPeopleVaccinatedCompleteByVaccinationDate("","New people fully vaccinated by vaccination date", false),
    newPeopleVaccinatedFirstDoseByPublishDate("","New people vaccinated 1st dose by publish date", false),
    newPeopleVaccinatedFirstDoseByVaccinationDate("","New people vaccinated with a first dose by vaccination date", false),
    newPeopleVaccinatedSecondDoseByPublishDate("","New people vaccinated 2nd dose by publish date", false),
    newPeopleVaccinatedSecondDoseByVaccinationDate("","New people vaccinated with a second dose by vaccination date", false),
    newPeopleVaccinatedThirdDoseByPublishDate("","New people vaccinated with a third dose by publish date", false),
    newPeopleVaccinatedThirdInjectionByPublishDate("","New people vaccinated with a booster dose plus new people vaccinated with a third dose by publish date", false),
    newPeopleVaccinatedThirdInjectionByVaccinationDate("","New people vaccinated with a booster or third dose by vaccination date", false),
    newPillarFourTestsByPublishDate("","New pillar 4 tests by publish date", false),
    newPillarOneTestsByPublishDate("","New pillar 1 tests by publish date", false),
    newPillarOneTwoTestsByPublishDate("","New pillars 1 and 2 tests by publish date", false),
    newPillarThreeTestsByPublishDate("","New pillar 3 tests by publish date", false),
    newPillarTwoTestsByPublishDate("","New pillar 2 tests by publish date", false),
    newReinfectionsBySpecimenDate("","New reinfections by specimen date", false),
    newReinfectionsBySpecimenDateChange("","New reinfections by specimen date change", false),
    newReinfectionsBySpecimenDateChangePercentage("","New reinfections change percentage by specimen date", false),
    newReinfectionsBySpecimenDateDirection("","New reinfections by specimen date direction", false),
    newReinfectionsBySpecimenDateRollingRate("","New reinfections rolling rate by specimen date", false),
    newReinfectionsBySpecimenDateRollingSum("","New reinfections rolling sum by specimen date", false),
    newTestsByPublishDate("","New tests by publish date", false),
    newVaccinesGivenByPublishDate("","New vaccines given by publish date", false),
    newVirusTestsByPublishDate("newVirusTestsByPublishDate","New virus tests", false),
    newVirusTestsByPublishDateChange("newVirusTestsByPublishDateChange","New virus tests by publish date change", false),
    newVirusTestsByPublishDateChangePercentage("newVirusTestsByPublishDateChangePercentage","New virus tests by publish date change percentage", false),
    newVirusTestsByPublishDateDirection("newVirusTestsByPublishDateDirection","New virus tests by publish date direction", false),
    newVirusTestsByPublishDateRollingSum("newVirusTestsByPublishDateRollingSum","New virus tests by publish date rolling sum", false),
    newVirusTestsBySpecimenDate("newVirusTestsBySpecimenDate","New virus tests by specimen date", false),
    newVirusTestsChange("newVirusTestsChange","New virus tests change", false),
    newVirusTestsChangePercentage("newVirusTestsChangePercentage","New virus tests change percentage", false),
    newVirusTestsDirection("newVirusTestsDirection","New virus tests direction", false),
    newVirusTestsRollingSum("newVirusTestsRollingSum","New virus tests rolling sum", false),
    newWeeklyNsoDeathsByRegDate("newWeeklyNsoDeathsByRegDate","New weekly national statistics office deaths by registration date", false),
    plannedAntibodyCapacityByPublishDate("plannedAntibodyCapacityByPublishDate","Planned antibody capacity by publish date", false),
    plannedCapacityByPublishDate("plannedCapacityByPublishDate","Planned capacity by publish date", false),
    plannedPCRCapacityByPublishDate("plannedPCRCapacityByPublishDate","Planned PCR capacity by publish date", false),
    previouslyReportedNewCasesBySpecimenDate("previouslyReportedNewCasesBySpecimenDate","Previously reported new cases by specimen date", false),
    transmissionRateGrowthRateMax("transmissionRateGrowthRateMax","Maximum transmission growth rate", false),
    transmissionRateGrowthRateMin("transmissionRateGrowthRateMin","Transmission rate growth rate min", false),
    transmissionRateMax("transmissionRateMax","Maximum transmission rate (R)", false),
    transmissionRateMin("transmissionRateMin","Minimum transmission rate (R)", false),
    uniqueCasePositivityBySpecimenDateRollingSum("uniqueCasePositivityBySpecimenDateRollingSum","Unique case positivity by specimen date rolling sum", false),
    uniquePeopleTestedBySpecimenDateRollingSum("uniquePeopleTestedBySpecimenDateRollingSum","Unique people tested by specimen date rolling sum", false),
    vaccinationsAgeDemographics("vaccinationsAgeDemographics","Vaccinations age demographics breakdown", false),
    VaccineRegisterPopulationByVaccinationDate("VaccineRegisterPopulationByVaccinationDate","Vaccination register (NIMS) population by vaccination date", false),
    weeklyPeopleVaccinatedFirstDoseByVaccinationDate("weeklyPeopleVaccinatedFirstDoseByVaccinationDate","Weekly people vaccinated 1st dose by vaccination date", false),
    weeklyPeopleVaccinatedSecondDoseByVaccinationDate("weeklyPeopleVaccinatedSecondDoseByVaccinationDate","Weekly people vaccinated 2nd dose by vaccination date", false);

    private final String metricNameValue;
    private final String metricDescription;
    private final Boolean isDeprecated;

    Metrics(String metricNameValue, String metricDescription, Boolean isDeprecated) {
        this.metricNameValue = metricNameValue;
        this.metricDescription = metricDescription;
        this.isDeprecated = isDeprecated;
    }
}
