package com.lmnoppy.api.covid.model.enums;

import lombok.Getter;

/**
 * All metrics avalable from the NHS Developer page: https://coronavirus.data.gov.uk/metrics
 *
 * metricNameValue - the actual metric name on NHS guide
 * metricDescription - description of what data the metric provides
 * isDeprecated - is the metric deprecated or not?
 *
 * Yes I will set all the ENUMS to upper case and add underscores....eventually.
 */

@Getter
public enum Metrics {

    DATE("date", null, false),
    AREA_NAME("areaName", null, false),
    AREA_CODE("areaCode", null, false),
    NEW_CASES_BY_PUBLISH_DATE("newCasesByPublishDate", null, false),
    CUM_CASES_BY_PUBLISH_DATE("cumCasesByPublishDate", "Cumulative cases by publish date", false),
    CUM_CASES_BY_PUBLISH_DATE_RATE("cumCasesByPublishDateRate", "Cumulative cases by publish date rate", false),
    NEW_DEATHS_28DAYS_BY_PUBLISH_DATE("newDeaths28DaysByPublishDate", null, false),
    CUM_DEATHS_28DAYS_BY_PUBLISH_DATE("cumDeaths28DaysByPublishDate", null, false),
    CUM_DEATHS_28DAYS_BY_PUBLISH_DATE_RATE("cumDeaths28DaysByPublishDateRate", "Cumulative deaths within 28 days of a positive test rate by publish date", false),
    COVID_OCCUPIED_MV_BEDS("covidOccupiedMVBeds", "COVID occupied mechanical ventilator beds", false),
    CUM_ADMISSIONS("cumAdmissions", "Cumulative admissions", false),
    CUM_ADMISSIONS_BY_AGE("cumAdmissionsByAge", "Cumulative admissions by age", false),
    CUM_ANTIBODY_TESTS_BY_PUBLISH_DATE("cumAntibodyTestsByPublishDate", "Cumulative antibody tests by publish date", false),
    CUM_CASES_LFD_CONFIRMED_PCR_BY_SPECIMEN_DATE("cumCasesLFDConfirmedPCRBySpecimenDate", "Cumulative cases LFD confirmed by PCR by specimen date", false),
    CUM_CASES_LFD_ONLY_BY_SPECIMEN_DATE("cumCasesLFDOnlyBySpecimenDate", "Cumulative cases LFD-only by specimen date", false),
    CUM_CASES_PCR_ONLY_BY_SPECIMEN_DATE("cumCasesPCROnlyBySpecimenDate", "Cumulative cases PCR only by specimen date", false),
    CUM_DAILY_NSO_DEATHS_BY_DEATH_DATE("cumDailyNsoDeathsByDeathDate", "Cumulative daily national statistics office deaths by death date", false),
    CUM_DEATHS_28DAYS_BY_DEATH_DATE("cumDeaths28DaysByDeathDate", "Cumulative deaths within 28 days of a positive test by death date", false),
    CUM_DEATHS_28DAYS_BY_DEATH_DATE_RATE("cumDeaths28DaysByDeathDateRate", "Cumulative deaths within 28 days of a positive test rate by death date", false),
    CUM_DEATHS60_DAYS_BY_DEATH_DATE("cumDeaths60DaysByDeathDate", "Cumulative deaths within 60 days of a positive test by death date", false),
    CUM_DEATHS_60DAYS_BY_DEATH_DATE_RATE("cumDeaths60DaysByDeathDateRate", "Cumulative deaths within 60 days of a positive test rate by death date", false),
    CUM_DEATHS_60DAYS_BY_PUBLISH_DATE("cumDeaths60DaysByPublishDate", "Cumulative deaths within 60 days of a positive test by publish date", false),
    CUM_DEATHS_60DAYS_BY_PUBLISH_DATE_RATE("cumDeaths60DaysByPublishDateRate", "Cumulative deaths within 60 days of a positive test rate by publish date", false),
    CUM_DEATHS_BY_DEATH_DATE("cumDeathsByDeathDate", "Cumulative deaths by death date", false),
    CUM_DEATHS_BY_DEATH_DATE_RATE("cumDeathsByDeathDateRate", "Cumulative deaths by death date rate", false),
    CUM_DEATHS_BY_PUBLISH_DATE("cumDeathsByPublishDate", "Cumulative deaths by publish date", false),
    CUM_DEATHS_BY_PUBLISH_DATE_RATE("cumDeathsByPublishDateRate", "Cumulative deaths by publish date rate", false),
    CUM_FIRST_EPISODES_BY_SPECIMEN_DATE("cumFirstEpisodesBySpecimenDate", "Cumulative first infection episodes by specimen date", false),
    CUM_FIRST_EPISODES_BY_SPECIMEN_DATE_RATE("cumFirstEpisodesBySpecimenDateRate", "Cumulative first infection episodes rate by specimen date", false),
    CUM_LFD_TESTS_BY_SPECIMEN_DATE("cumLFDTestsBySpecimenDate", "Cumulative LFD tests", false),
    CUM_ONS_DEATHS_BY_REGISTRATION_DATE("cumOnsDeathsByRegistrationDate", "Cumulative Office for National Statistics deaths by registration date", false),
    CUM_ONS_DEATHS_BY_REGISTRATION_DATE_RATE("cumOnsDeathsByRegistrationDateRate", "Cumulative ONS deaths by registration date rate", false),
    CUM_PCR_TESTS_BY_PUBLISH_DATE("cumPCRTestsByPublishDate", "Cumulative PCR tests by publish date", false),
    CUM_PCR_TESTS_BY_SPECIMEN_DATE("cumPCRTestsBySpecimenDate", "Total PCR tests by specimen date", false),
    CUM_PEOPLE_VACCINATED_BOOSTER_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedBoosterDoseByPublishDate", "Cumulative people vaccinated booster dose by publish date", false),
    CUM_PEOPLE_VACCINATED_COMPLETE_BY_PUBLISH_DATE("cumPeopleVaccinatedCompleteByPublishDate", "Cumulative people vaccinated complete by publish date", true),
    CUM_PEOPLE_VACCINATED_COMPLETE_BY_VACCINATION_DATE("cumPeopleVaccinatedCompleteByVaccinationDate", "Cumulative people fully vaccinated by vaccination date", true),
    CUM_PEOPLE_VACCINATED_FIRST_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedFirstDoseByPublishDate", "Cumulative people vaccinated 1st dose by publish date", false),
    CUM_PEOPLE_VACCINATED_FIRST_DOSE_BY_VACCINATION_DATE("cumPeopleVaccinatedFirstDoseByVaccinationDate", "Cumulative people vaccinated 1st dose by vaccination date", false),
    CUM_PEOPLE_VACCINATED_SECOND_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedSecondDoseByPublishDate", "Cumulative people vaccinated 2nd dose by publish date", false),
    CUM_PEOPLE_VACCINATED_SECOND_DOSE_BY_VACCINATION_DATE("cumPeopleVaccinatedSecondDoseByVaccinationDate", "Cumulative people vaccinated 2nd dose by vaccination date", false),
    CUM_PEOPLE_VACCINATED_THIRD_DOSE_BY_PUBLISH_DATE("cumPeopleVaccinatedThirdDoseByPublishDate", "Cumulative people vaccinated 3rd dose by publish date", false),
    CUM_PEOPLE_VACCINATED_THIRD_INJECTION_BY_PUBLISH_DATE("cumPeopleVaccinatedThirdInjectionByPublishDate", "Cumulative people vaccinated with a booster dose plus new people vaccinated with a third dose by publish date", false),
    CUM_PEOPLE_VACCINATED_THIRD_INJECTION_BY_VACCINATION_DATE("cumPeopleVaccinatedThirdInjectionByVaccinationDate", "Cumulative people vaccinated booster or third dose by vaccination date", false),
    CUM_PILLAR_FOUR_TESTS_BY_PUBLISH_DATE("cumPillarFourTestsByPublishDate", "Cumulative pillar 4 tests by publish date", false),
    CUM_PILLAR_ONE_TESTS_BY_PUBLISH_DATE("cumPillarOneTestsByPublishDate", "Cumulative pillar 1 tests by publish date", false),
    CUM_PILLAR_ONE_TWO_TESTS_BY_PUBLISH_DATE("cumPillarOneTwoTestsByPublishDate", "Cumulative pillars 1 and 2 tests by publish date", false),
    CUM_PILLAR_THREE_TESTS_BY_PUBLISH_DATE("cumPillarThreeTestsByPublishDate", "Cumulative pillar 3 tests by publish date", false),
    CUM_PILLAR_TWO_TESTS_BY_PUBLISH_DATE("cumPillarTwoTestsByPublishDate", "Cumulative pillar 2 tests by publish date", false),
    CUM_REINFECTIONS_BY_SPECIMEN_DATE("cumReinfectionsBySpecimenDate", "Cumulative reinfections by specimen date", false),
    CUM_REINFECTIONS_BY_SPECIMEN_DATE_RATE("cumReinfectionsBySpecimenDateRate", "Cumulative reinfections rate by specimen date", false),
    CUM_TESTS_BY_PUBLISH_DATE("cumTestsByPublishDate", "Cumulative tests by publish date", false),
    CUM_VACCINATION_BOOSTER_DOSE_UPTAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationBoosterDoseUptakeByPublishDatePercentage", "Cumulative percentage of people vaccinated with a booster dose by publish date", false),
    CUM_VACCINATION_COMPLETE_COVERAGE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationCompleteCoverageByPublishDatePercentage", "Cumulative vaccination complete coverage by publish date percentage", true),
    CUM_VACCINATION_COMPLETE_COVERAGE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationCompleteCoverageByVaccinationDatePercentage", "Cumulative percentage of people fully vaccinated by vaccination date", true),
    CUM_VACCINATION_FIRST_DOSE_UPTAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationFirstDoseUptakeByPublishDatePercentage", "Cumulative vaccination 1st dose uptake by publish date percentage", false),
    CUM_VACCINATION_FIRST_DOSE_UPTAKE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationFirstDoseUptakeByVaccinationDatePercentage", "Cumulative percentage of people vaccinated with a first dose by vaccination date", false),
    CUM_VACCINATION_SECOND_DOSE_UP_TAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationSecondDoseUptakeByPublishDatePercentage", "Cumulative vaccination 2nd dose uptake by publish date percentage", false),
    CUM_VACCINATION_SECOND_DOSE_UPTAKE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationSecondDoseUptakeByVaccinationDatePercentage", "Cumulative percentage of second dose vaccination uptake by vaccination date", false),
    CUM_VACCINATION_THIRD_INJECTION_UPTAKE_BY_PUBLISH_DATE_PERCENTAGE("cumVaccinationThirdInjectionUptakeByPublishDatePercentage", "Cumulative percentage of people vaccinated with a booster dose plus people vaccinated with third dose by publish date", false),
    CUM_VACCINATION_THIRD_INJECTION_UPTAKE_BY_VACCINATION_DATE_PERCENTAGE("cumVaccinationThirdInjectionUptakeByVaccinationDatePercentage", "Cumulative percentage of people vaccinated with a booster or third dose by vaccination date", false),
    CUM_VACCINES_GIVEN_BY_PUBLISH_DATE("cumVaccinesGivenByPublishDate", "Cumulative vaccines given by publish date", false),
    CUM_VIRUS_TESTS_BY_PUBLISH_DATE("cumVirusTestsByPublishDate", "Cumulative virus tests", false),
    CUM_VIRUS_TESTS_BY_SPECIMEN_DATE("cumVirusTestsBySpecimenDate", "Total virus tests by specimen date", false),
    CUM_WEEKLY_NSO_DEATHS_BY_REG_DATE("cumWeeklyNsoDeathsByRegDate", "Cumulative weekly national statistics office deaths by registration date", false),
    CUM_WEEKLY_NSO_DEATHS_BY_REG_DATE_RATE("cumWeeklyNsoDeathsByRegDateRate","Cumulative weekly national statistics office deaths by registration date rate", false),
    FEMALE_CASES("femaleCases","Female cases", false),
    FEMALE_DEATHS_28DAYS("femaleDeaths28Days","Female deaths within 28 days of a positive test", false),
    HOSPITAL_CASES("hospitalCases","Patients in hospital", false),
    MALE_CASES("maleCases","Male cases", false),
    MALE_DEATHS_28DAYS("maleDeaths28Days","Male deaths within 28 days of a positive test", false),
    NEW_ADMISSIONS("newAdmissions","New admissions", false),
    NEW_ADMISSIONS_CHANGE("newAdmissionsChange","New admissions change", false),
    NEW_ADMISSIONS_CHANGE_PERCENTAGE("newAdmissionsChangePercentage","New admissions change percentage", false),
    NEW_ADMISSIONS_DIRECTION("newAdmissionsDirection","New admissions direction", false),
    NEW_ADMISSIONS_ROLLING_RATE("newAdmissionsRollingRate","New admissions rolling rate", false),
    NEW_ADMISSIONS_ROLLING_SUM("newAdmissionsRollingSum","New admissions rolling sum", false),
    NEW_ANTIBODY_TESTS_BY_PUBLISH_DATE("newAntibodyTestsByPublishDate","New antibody tests by publish date", false),
    NEW_CASES_BY_PUBLISH_DATE_CHANGE("newCasesByPublishDateChange","New cases by publish date change", false),
    NEW_CASES_BY_PUBLISH_DATE_CHANGE_PERCENTAGE("newCasesByPublishDateChangePercentage","New cases percentage change by publish date", false),
    NEW_CASES_BY_PUBLISH_DATE_DIRECTION("newCasesByPublishDateDirection","New cases by publish date direction", false),
    NEW_CASES_BY_PUBLISH_DATE_ROLLING_SUM("newCasesByPublishDateRollingSum","New cases by publish date rolling sum", false),
    NEW_CASES_BY_SPECIMEN_DATE("newCasesBySpecimenDate","New cases by specimen date", false),
    NEW_CASES_BY_SPECIMEN_DATE_AGE_DEMOGRAPHICS("newCasesBySpecimenDateAgeDemographics","New cases by specimen date age demographics", false),
    NEW_CASES_BY_SPECIMEN_DATE_CHANGE("newCasesBySpecimenDateChange","New cases by specimen date change", false),
    NEW_CASES_BY_SPECIMEN_DATE_CHANGE_PERCENTAGE("newCasesBySpecimenDateChangePercentage","New cases percentage change by specimen date", false),
    NEW_CASES_BY_SPECIMEN_DATE_DIRECTION("newCasesBySpecimenDateDirection","New cases by specimen date direction", false),
    NEW_CASES_BY_SPECIMEN_DATE_ROLLING_RATE("newCasesBySpecimenDateRollingRate","New cases rolling rate by specimen date", false),
    NEW_CASES_BY_SPECIMEN_DATE_ROLLING_SUM("newCasesBySpecimenDateRollingSum","New cases by specimen date rolling sum", false),
    NEW_CASES_LFD_CONFIRMED_PCR_BY_SPECIMEN_DATE("newCasesLFDConfirmedPCRBySpecimenDate","New cases LFD confirmed by PCR by specimen date", false),
    NEW_CASES_LFD_CONFIRMED_PCR_BY_SPECIMEN_DATE_ROLLING_RATE("newCasesLFDConfirmedPCRBySpecimenDateRollingRate","New cases LFD confirmed by PCR rolling rate by specimen date", false),
    NEW_CASES_LFD_CONFIRMED_PCR_BY_SPECIMEN_DATE_ROLLING_SUM("newCasesLFDConfirmedPCRBySpecimenDateRollingSum","New cases LFD confirmed by PCR rolling sum by specimen date", false),
    NEW_CASES_LFD_ONLY_BY_SPECIMEN_DATE("newCasesLFDOnlyBySpecimenDate","New cases LFD only by specimen date", false),
    NEW_CASES_LFD_ONLY_BY_SPECIMEN_DATE_ROLLING_RATE("newCasesLFDOnlyBySpecimenDateRollingRate","New cases LFD only rolling rate by specimen date", false),
    NEW_CASES_LFD_ONLY_BY_SPECIMEN_DATE_ROLLING_SUM("newCasesLFDOnlyBySpecimenDateRollingSum","New cases LFD only rolling sum by specimen date", false),
    NEW_CASES_PCR_ONLY_BY_SPECIMEN_DATE("newCasesPCROnlyBySpecimenDate","New cases PCR only by specimen date", false),
    NEW_CASES_PCR_ONLY_BY_SPECIMEN_DATE_ROLLING_RATE("newCasesPCROnlyBySpecimenDateRollingRate","New cases PCR only by specimen date rolling rate", false),
    NEW_CASES_PCR_ONLY_BY_SPECIMEN_DATE_ROLLING_SUM("newCasesPCROnlyBySpecimenDateRollingSum","New cases PCR only by specimen date rolling sum", false),
    NEW_DAILY_NSO_DEATHS_BY_DEATH_DATE("newDailyNsoDeathsByDeathDate","New daily national statistics office deaths by death date", false),
    new_Deaths28DaysByDeathDate("newDeaths28DaysByDeathDate","New deaths within 28 days of a positive test by death date", false),
    new_Deaths28DaysByDeathDateAgeDemographics("newDeaths28DaysByDeathDateAgeDemographics","New deaths 28 days by death date age demographics", false),
    new_Deaths28DaysByDeathDateChangePercentage("newDeaths28DaysByDeathDateChangePercentage","New deaths within 28 days of a positive test change percentage by death date", false),
    new_Deaths28DaysByDeathDateDirection("newDeaths28DaysByDeathDateDirection","New deaths within 28 days of a positive test direction by death date", false),
    new_Deaths28DaysByDeathDateRate("newDeaths28DaysByDeathDateRate","New deaths within 28 days of a positive test rate by death date", false),
    new_Deaths28DaysByDeathDateRollingRate("newDeaths28DaysByDeathDateRollingRate","New deaths within 28 days of a positive test rolling rate by death date", false),
    new_Deaths28DaysByDeathDateRollingSum("newDeaths28DaysByDeathDateRollingSum","New deaths within 28 days of a positive test rolling sum test by death date", false),
    new_Deaths28DaysByPublishDate("newDeaths28DaysByPublishDate","New deaths 28 days of a positive test by publish date", false),
    new_Deaths28DaysByPublishDateChange("newDeaths28DaysByPublishDateChange","New deaths within 28 days of a positive test by publish date change", false),
    new_Deaths28DaysByPublishDateChangePercentage("newDeaths28DaysByPublishDateChangePercentage","New deaths within 28 days of a positive test change percentage by publish date", false),
    new_Deaths28DaysByPublishDateDirection("newDeaths28DaysByPublishDateDirection","New deaths within 28 days of a positive test direction by publish date", false),
    new_Deaths28DaysByPublishDateRollingSum("newDeaths28DaysByPublishDateRollingSum","New deaths within 28 days of a positive test rolling sum by publish date", false),
    new_Deaths60DaysByDeathDate("newDeaths60DaysByDeathDate","New deaths within 60 days of a positive test by death date", false),
    new_Deaths60DaysByDeathDateRate("newDeaths60DaysByDeathDateRate","New deaths within 60 days of a positive test rate by death date", false),
    new_Deaths60DaysByDeathDateRollingRate("newDeaths60DaysByDeathDateRollingRate","New deaths within 60 days of a positive test rolling rate by death date", false),
    new_Deaths60DaysByDeathDateRollingSum("newDeaths60DaysByDeathDateRollingSum","New deaths within 60 days of a positive test rolling sum by death date", false),
    new_Deaths60DaysByPublishDate("newDeaths60DaysByPublishDate","New deaths within 60 days of a positive test by publish date", false),
    new_DeathsByDeathDate("newDeathsByDeathDate","New deaths by death date", false),
    new_DeathsByDeathDateRate("newDeathsByDeathDateRate","New deaths by death date rate", false),
    new_DeathsByDeathDateRollingRate("newDeathsByDeathDateRollingRate","New deaths by death date rolling rate", false),
    new_DeathsByDeathDateRollingSum("newDeathsByDeathDateRollingSum","New deaths by death date rolling sum", false),
    new_DeathsByPublishDate("newDeathsByPublishDate","New deaths by publish date", false),
    new_FirstEpisodesBySpecimenDate("newFirstEpisodesBySpecimenDate","New first episodes by specimen date", false),
    new_FirstEpisodesBySpecimenDateChange("newFirstEpisodesBySpecimenDateChange","New first episodes by specimen date change", false),
    new_FirstEpisodesBySpecimenDateChangePercentage("","New first episodes change percentage by specimen date", false),
    new_FirstEpisodesBySpecimenDateDirection("","New first episodes direction by specimen date", false),
    new_FirstEpisodesBySpecimenDateRollingRate("","New first episodes rolling rate by specimen date", false),
    new_FirstEpisodesBySpecimenDateRollingSum("","New first infection episodes rolling sum by specimen date", false),
    new_LFDTestsBySpecimenDate("","New LFD tests", false),
    new_OnsDeathsByRegistrationDate("","New Office for National Statistics deaths by registration date", false),
    new_PCRTestsByPublishDate("","New PCR tests by publish date", false),
    new_PCRTestsByPublishDateChange("","New PCR tests by publish date change", false),
    new_PCRTestsByPublishDateChangePercentage("","New PCR tests by publish date change percentage", false),
    new_PCRTestsByPublishDateDirection("","New PCR tests by publish date direction", false),
    new_PCRTestsByPublishDateRollingSum("","New PCR tests by publish date rolling sum", false),
    new_PCRTestsBySpecimenDate("","New PCR tests by specimen date", false),
    new_PeopleReceivingFirstDose("","New people receiving 1st dose", false),
    new_PeopleReceivingSecondDose("","New people receiving 2nd dose", false),
    new_PeopleVaccinatedBoosterDoseByPublishDate("","New people vaccinated with a booster dose by publish date", false),
    new_PeopleVaccinatedCompleteByPublishDate("","New people vaccinated complete by publish date", false),
    new_PeopleVaccinatedCompleteByVaccinationDate("","New people fully vaccinated by vaccination date", false),
    new_PeopleVaccinatedFirstDoseByPublishDate("","New people vaccinated 1st dose by publish date", false),
    new_PeopleVaccinatedFirstDoseByVaccinationDate("","New people vaccinated with a first dose by vaccination date", false),
    new_PeopleVaccinatedSecondDoseByPublishDate("","New people vaccinated 2nd dose by publish date", false),
    new_PeopleVaccinatedSecondDoseByVaccinationDate("","New people vaccinated with a second dose by vaccination date", false),
    new_PeopleVaccinatedThirdDoseByPublishDate("","New people vaccinated with a third dose by publish date", false),
    new_PeopleVaccinatedThirdInjectionByPublishDate("","New people vaccinated with a booster dose plus new people vaccinated with a third dose by publish date", false),
    new_PeopleVaccinatedThirdInjectionByVaccinationDate("","New people vaccinated with a booster or third dose by vaccination date", false),
    NEW_PILLAR_FOUR_TESTS_BY_PUBLISH_DATE("","New pillar 4 tests by publish date", false),
    NEW_PILLAR_ONE_TESTS_BY_PUBLISH_DATE("","New pillar 1 tests by publish date", false),
    NEW_PILLAR_ONE_TWO_TESTS_BY_PUBLISH_DATE("","New pillars 1 and 2 tests by publish date", false),
    NEW_PILLAR_THREE_TESTS_BY_PUBLISH_DATE("","New pillar 3 tests by publish date", false),
    NEW_PILLAR_TWO_TESTS_BY_PUBLISH_DATE("","New pillar 2 tests by publish date", false),
    NEW_REINFECTIONS_BY_SPECIMEN_DATE("","New reinfections by specimen date", false),
    NEW_REINFECTIONS_BY_SPECIMEN_DATE_CHANGE("","New reinfections by specimen date change", false),
    NEW_REINFECTIONS_BY_SPECIMEN_DATE_CHANGE_PERCENTAGE("","New reinfections change percentage by specimen date", false),
    NEW_REINFECTIONS_BY_SPECIMEN_DATE_DIRECTION("","New reinfections by specimen date direction", false),
    NEW_REINFECTIONS_BY_SPECIMEN_DATE_ROLLING_RATE("","New reinfections rolling rate by specimen date", false),
    NEW_REINFECTIONS_BY_SPECIMEN_DATE_ROLLING_SUM("","New reinfections rolling sum by specimen date", false),
    NEW_TESTS_BY_PUBLISH_DATE("","New tests by publish date", false),
    NEW_VACCINES_GIVEN_BY_PUBLISH_DATE("","New vaccines given by publish date", false),
    NEW_VIRUS_TESTS_BY_PUBLISH_DATE("newVirusTestsByPublishDate","New virus tests", false),
    NEW_VIRUS_TESTS_BY_PUBLISH_DATE_CHANGE("newVirusTestsByPublishDateChange","New virus tests by publish date change", false),
    NEW_VIRUS_TESTS_BY_PUBLISH_DATE_CHANGE_PERCENTAGE("newVirusTestsByPublishDateChangePercentage","New virus tests by publish date change percentage", false),
    NEW_VIRUS_TESTS_BY_PUBLISH_DATE_DIRECTION("newVirusTestsByPublishDateDirection","New virus tests by publish date direction", false),
    NEW_VIRUS_TESTS_BY_PUBLISH_DATE_ROLLINGSUM("newVirusTestsByPublishDateRollingSum","New virus tests by publish date rolling sum", false),
    NEW_VIRUS_TESTS_BY_SPECIMEN_DATE("newVirusTestsBySpecimenDate","New virus tests by specimen date", false),
    NEW_VIRUS_TESTS_CHANGE("newVirusTestsChange","New virus tests change", false),
    NEW_VIRUS_TESTS_CHANGE_PERCENTAGE("newVirusTestsChangePercentage","New virus tests change percentage", false),
    NEW_VIRUS_TESTS_DIRECTION("newVirusTestsDirection","New virus tests direction", false),
    NEW_VIRUS_TESTS_ROLLING_SUM("newVirusTestsRollingSum","New virus tests rolling sum", false),
    NEW_WEEKLY_NSO_DEATHS_BY_REG_DATE("newWeeklyNsoDeathsByRegDate","New weekly national statistics office deaths by registration date", false),
    plannedAntibodyCapacityByPublishDate("plannedAntibodyCapacityByPublishDate","Planned antibody capacity by publish date", false),
    plannedCapacityByPublishDate("plannedCapacityByPublishDate","Planned capacity by publish date", false),
    plannedPCRCapacityByPublishDate("plannedPCRCapacityByPublishDate","Planned PCR capacity by publish date", false),
    previouslyReportedNewCasesBySpecimenDate("previouslyReportedNewCasesBySpecimenDate","Previously reported new cases by specimen date", false),
    transmissionRateGrowthRateMax("transmissionRateGrowthRateMax","Maximum transmission growth rate", false),
    transmissionRateGrowthRateMin("transmissionRateGrowthRateMin","Transmission rate growth rate min", false),
    transmissionRateMax("transmissionRateMax","Maximum transmission rate (R)", false),
    transmissionRateMin("transmissionRateMin","Minimum transmission rate (R)", false),
    uniqueCasePositivityBySpecimenDateRollingSum("uniqueCasePositivityBySpecimenDateRollingSum","Unique case positivity by specimen date rolling sum", false),
    uniquePeopleTestedBySpecimenDateRollingSum("uniquePeopleTestedBySpecimenDateRollingSum","Unique people tested by specimen date rolling sum", false),
    vaccinationsAgeDemographics("vaccinationsAgeDemographics","Vaccinations age demographics breakdown", false),
    VaccineRegisterPopulationByVaccinationDate("VaccineRegisterPopulationByVaccinationDate","Vaccination register (NIMS) population by vaccination date", false),
    weeklyPeopleVaccinatedFirstDoseByVaccinationDate("weeklyPeopleVaccinatedFirstDoseByVaccinationDate","Weekly people vaccinated 1st dose by vaccination date", false),
    weeklyPeopleVaccinatedSecondDoseByVaccinationDate("weeklyPeopleVaccinatedSecondDoseByVaccinationDate","Weekly people vaccinated 2nd dose by vaccination date", false);

    private final String metricNameValue;
    private final String metricDescription;
    private final Boolean isDeprecated;

    Metrics(String metricNameValue, String metricDescription, Boolean isDeprecated) {
        this.metricNameValue = metricNameValue;
        this.metricDescription = metricDescription;
        this.isDeprecated = isDeprecated;
    }
}
