package com.lmnoppy.api.covid.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;

import java.io.Serializable;

@Data
@JsonIgnoreProperties(ignoreUnknown = true)
public class MetricsData implements Serializable {

    private static final long serialVersionUID = -417331668877851283L;

    private String date;

    private String areaName;
    private String areaCode;

    private String newCasesByPublishDate;
    private String cumCasesByPublishDate;
    private String cumDeaths28DaysByPublishDate;
    private String newDeaths28DaysByPublishDate;
    private String cumDeaths28DaysByPublishDateRate;
    private String covidOccupiedMVBeds;
    private String cumAdmissions;
    private Age[] cumAdmissionsByAge;
    private String cumCasesPCROnlyBySpecimenDate;
    private String cumDailyNsoDeathsByDeathDate;
    private String cumDeaths28DaysByDeathDate;
    private String cumDeaths28DaysByDeathDateRate;
    private String cumDeaths60DaysByDeathDate;
    private String cumDeaths60DaysByDeathDateRate;
    private String cumDeaths60DaysByPublishDate;
    private String cumDeaths60DaysByPublishDateRate;
    private String cumDeathsByDeathDate;
    private String cumDeathsByDeathDateRate;
    private String cumDeathsByPublishDate;
    private String cumDeathsByPublishDateRate;
    private String cumFirstEpisodesBySpecimenDate;
    private String cumFirstEpisodesBySpecimenDateRate;
    private String cumLFDTestsBySpecimenDate;
    private String cumOnsDeathsByRegistrationDate;
    private String cumOnsDeathsByRegistrationDateRate;
    private String cumPCRTestsByPublishDate;
    private String cumPCRTestsBySpecimenDate;
    private String cumPeopleVaccinatedBoosterDoseByPublishDate;
    private String cumPeopleVaccinatedCompleteByPublishDate;
    private String cumPeopleVaccinatedCompleteByVaccinationDate;
    private String cumPeopleVaccinatedFirstDoseByPublishDate;
    private String cumPeopleVaccinatedFirstDoseByVaccinationDate;
    private String cumPeopleVaccinatedSecondDoseByPublishDate;
    private String cumPeopleVaccinatedSecondDoseByVaccinationDate;
    private String cumPeopleVaccinatedThirdDoseByPublishDate;
    private String cumPeopleVaccinatedThirdInjectionByPublishDate;
    private String cumPeopleVaccinatedThirdInjectionByVaccinationDate;
    private String cumReinfectionsBySpecimenDate;
    private String cumReinfectionsBySpecimenDateRate;
    private String cumTestsByPublishDate;
    private String cumVaccinationBoosterDoseUptakeByPublishDatePercentage;
    private String cumVaccinationCompleteCoverageByPublishDatePercentage;
    private String cumVaccinationCompleteCoverageByVaccinationDatePercentage;
    private String cumVaccinationFirstDoseUptakeByPublishDatePercentage;
    private String cumVaccinationFirstDoseUptakeByVaccinationDatePercentage;
    private String cumVaccinationSecondDoseUptakeByPublishDatePercentage;
    private String cumVaccinationSecondDoseUptakeByVaccinationDatePercentage;
    private String cumVaccinationThirdInjectionUptakeByPublishDatePercentage;
    private String cumVaccinationThirdInjectionUptakeByVaccinationDatePercentage;
    private String cumVaccinesGivenByPublishDate;
    private String cumVirusTestsByPublishDate;
    private String cumVirusTestsBySpecimenDate;
    private String cumWeeklyNsoDeathsByRegDate;
    private String cumWeeklyNsoDeathsByRegDateRate;
    private Age[] femaleCases;
    private Age[] femaleDeaths28Days;
    private String hospitalCases;
    private Age[] maleCases;
    private Age[] maleDeaths28Days;
    private String newAdmissions;
    private String newAdmissionsChange;
    private String newAdmissionsChangePercentage;
    private String newAdmissionsDirection;
    private String newAdmissionsRollingRate;
    private String newAdmissionsRollingSum;
    private String newAntibodyTestsByPublishDate;
    private String newCasesByPublishDateChange;
    private String newCasesByPublishDateChangePercentage;
    private String newCasesByPublishDateDirection;
    private String newCasesByPublishDateRollingSum;
    private String newCasesBySpecimenDate;
    private String newCasesBySpecimenDateAgeDemographics;
    private String newCasesBySpecimenDateChange;
    private String newCasesBySpecimenDateChangePercentage;
    private String newCasesBySpecimenDateDirection;
    private String newCasesBySpecimenDateRollingRate;
    private String newCasesBySpecimenDateRollingSum;
    private String newCasesLFDConfirmedPCRBySpecimenDate;
    private String newCasesLFDConfirmedPCRBySpecimenDateRollingRate;
    private String newCasesLFDConfirmedPCRBySpecimenDateRollingSum;
    private String newCasesLFDOnlyBySpecimenDate;
    private String newCasesLFDOnlyBySpecimenDateRollingRate;
    private String newCasesLFDOnlyBySpecimenDateRollingSum;
    private String newCasesPCROnlyBySpecimenDate;
    private String newCasesPCROnlyBySpecimenDateRollingRate;
    private String newCasesPCROnlyBySpecimenDateRollingSum;
    private String newDailyNsoDeathsByDeathDate;
    private String newDeaths28DaysByDeathDate;
    private String newDeaths28DaysByDeathDateAgeDemographics;
    private String newDeaths28DaysByDeathDateChangePercentage;
    private String newDeaths28DaysByDeathDateDirection;
    private String newDeaths28DaysByDeathDateRate;
    private String newDeaths28DaysByDeathDateRollingRate;
    private String newDeaths28DaysByDeathDateRollingSum;
    private String newDeaths28DaysByPublishDateChange;
    private String newDeaths28DaysByPublishDateChangePercentage;
    private String newDeaths28DaysByPublishDateDirection;
    private String newDeaths28DaysByPublishDateRollingSum;
    private String newDeaths60DaysByDeathDate;
    private String newDeaths60DaysByDeathDateRate;
    private String newDeaths60DaysByDeathDateRollingRate;
    private String newDeaths60DaysByDeathDateRollingSum;
    private String newDeaths60DaysByPublishDate;
    private String newDeathsByDeathDate;
    private String newDeathsByDeathDateRate;
    private String newDeathsByDeathDateRollingRate;
    private String newDeathsByDeathDateRollingSum;
    private String newDeathsByPublishDate;
    private String newFirstEpisodesBySpecimenDate;
    private String newFirstEpisodesBySpecimenDateChange;
    private String newPillarFourTestsByPublishDate;
    private String newVirusTestsByPublishDate;
    private String newVirusTestsByPublishDateChange;
    private String newVirusTestsByPublishDateChangePercentage;
    private String newVirusTestsByPublishDateDirection;
    private String newVirusTestsByPublishDateRollingSum;
    private String newVirusTestsBySpecimenDate;
    private String newVirusTestsChange;
    private String newVirusTestsChangePercentage;
    private String newVirusTestsDirection;
    private String newVirusTestsRollingSum;
    private String newWeeklyNsoDeathsByRegDate;
    private String plannedAntibodyCapacityByPublishDate;
    private String plannedCapacityByPublishDate;
    private String plannedPCRCapacityByPublishDate;
    private String previouslyReportedNewCasesBySpecimenDate;
    private String transmissionRateGrowthRateMax;
    private String transmissionRateGrowthRateMin;
    private String transmissionRateMax;
    private String transmissionRateMin;
    private String uniqueCasePositivityBySpecimenDateRollingSum;
    private String uniquePeopleTestedBySpecimenDateRollingSum;
    private String vaccinationsAgeDemographics;
    private String vaccineRegisterPopulationByVaccinationDate;
    private String weeklyPeopleVaccinatedFirstDoseByVaccinationDate;
    private String weeklyPeopleVaccinatedSecondDoseByVaccinationDate;
    private String newPillarOneTestsByPublishDate;
}
