name: "Feature PR build"

on:
  pull_request:
    branches: [ main, release/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'microsoft'
        java-package: jdk
        cache: maven

    - name: Build with Maven
      run: mvn --B --update-snapshots verify

